public class ClassToBeTested {
    public static Integer addNumbers(Integer a, Integer b) {
        Integer sum = a + b;
        return sum;
    }
    //Update test - feature branch 2
    //New line with feature branch 2
    //New line with feature branch 3
    //2nd new line with 2nd commit on feature branch 3
    
     public static Integer substractNumbers(Integer a, Integer b) {
        Integer substract = a - b;
        return substract;
    }
    
     public static Integer multiplyNumbers(Integer a, Integer b) {
        Integer multiply = a * b;
        return multiply;
    }
}